// Auto-generated from Twelve Data /stocks?country=Pakistan API
// Source: https://api.twelvedata.com/stocks?country=Pakistan&format=JSON
// Total: 459 PSX-listed companies (live from Twelve Data)
// Generated: 2026-08-25T19:41:13.164492

export interface TwelveDataStock {
  symbol: string;
  name: string;
  exchange: string;
  mic_code: string;
  country: string;
  currency: string;
  type: string;
}

export const TWELVE_DATA_PSX_LIST: TwelveDataStock[] = [
  { symbol: "1ALN", name: "First Al-Noor Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "1CSC", name: "First Capital Securities Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "1IMD", name: "First Imrooz Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "1PRM", name: "First Prudential Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "1PUJ", name: "First Punjab Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ABBT", name: "Abbott Laboratories Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ABDU", name: "Abdullah Shah Ghazi Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ABL", name: "Allied Bank Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ADAM", name: "Adamjee Life Assurance Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ADIN", name: "Adamjee Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ADML", name: "Artistic Denim Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ADSU", name: "Adam Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AGHA", name: "Agha Steel Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AGLI", name: "Agritech Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AGPL", name: "AGP Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AGRT", name: "Agriauto Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AHL", name: "Arif Habib Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AHTM", name: "Ahmad Hassan Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AIRL", name: "Air Link Communication Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AISH", name: "Aisha Steel Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AISH_p", name: "Aisha Steel Mills Ltd Pref", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Preferred Stock" },
  { symbol: "AISH_pa", name: "Aisha Steel Mills Ltd Pref Conv", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Preferred Stock" },
  { symbol: "AKDH", name: "AKD Hospitality Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AKDS", name: "AKD Securities Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AKGL", name: "Al-Khair Gadoon Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALBS", name: "AL-Abbas Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALGH", name: "Al-Ghazi Tractors Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALIS", name: "Ali Asghar Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALNS", name: "Al Noor Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALSH", name: "Al Shaheer Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ALTN", name: "Altern Energy Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AMBL", name: "Apna Microfinance Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AMST", name: "Amreli Steels Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AMTX", name: "Amtex Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AMZN", name: "Meezan Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ANTM", name: "An Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "APL", name: "Attock Petroleum Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ARCH", name: "Archroma Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ARIF", name: "Arif Habib Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ARPK", name: "Arpak International Investment Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ARUJ", name: "Aruj Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASBK", name: "Askari Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASFQ", name: "Ashfaq Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASIN", name: "Asia Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASKA", name: "Askari Life Assurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASKI", name: "Askari General Insurance Co", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ASMT", name: "Asim Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATHO", name: "Atlas Honda Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATIL", name: "Atlas Insurance Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATLA", name: "Atlas Battery Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATML", name: "Arctic Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATOC", name: "Attock Cement Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATOR", name: "Attock Refinery Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ATTA", name: "At-Tahur Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AVAN", name: "Avanceon Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "AZNL", name: "Azgard Nine Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BABA", name: "Baba Farid Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BAFL", name: "Bank Alfalah Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BANK", name: "Summit Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BANU", name: "Bannu Woollen Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BATA", name: "Bata Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BAWA", name: "Bawany Air Products Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BAWH", name: "Baluchistan Wheels Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BECO", name: "Beco Steel Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BELT", name: "Bela Automotives Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BERG", name: "Berger Paints Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BEST", name: "Bestway Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BFIN", name: "Biafo Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BFMD", name: "B F Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BGLS", name: "Balochistan Glass Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BHAN", name: "Bhanero Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BIFB", name: "Bilal Fibres Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BIPL", name: "BankIslami Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BKEQ", name: "Bank Al-Habib Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BLET", name: "Blessed Textiles Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BLPL", name: "Burshane LPG (Pakistan) Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BLUE", name: "Blue Ex Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BOK", name: "Bank of Khyber", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BOLC", name: "Bolan Casting Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BOPU", name: "Bank of Punjab", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BRRG", name: "Brr Guardian Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BUNN", name: "Bunny's Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "BUXL", name: "Buxly Paints Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CALC", name: "Calcorp Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CENP", name: "Century Paper & Board Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CHBL", name: "Chenab Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CHPR", name: "Cherat Packaging Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CHRC", name: "Cherat Cement Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CHSL", name: "Chakwal Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CHSU", name: "Chashma Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CITI", name: "Citi Pharma Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CLCP_p", name: "Chenab Ltd Pref", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Preferred Stock" },
  { symbol: "CLVF", name: "Clover Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CNER", name: "Cinergyco PK Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "COLG", name: "Colgate-Palmolive Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CORD", name: "Cordoba Logistics Ventures Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CREJ", name: "Crescent Jute Products Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CRES", name: "Crescent Cotton Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CRFB", name: "Crescent Fibres Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CRIN", name: "Century Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CRST", name: "Crescent Steel & Allied Products Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CRTX", name: "Crescent Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CSTR", name: "Crescent Star Insurance Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "CTML", name: "Colony Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DADC", name: "Dadabhoy Cement Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DAET", name: "Dadex Eternit Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DAGL", name: "Data Agro Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DANC", name: "Dandot Cement Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DARS", name: "Dar Es Salaam Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DAWH", name: "Engro Holdings Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DECE", name: "Dewan Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DEFM", name: "Dewan Farooque Motors Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DEL", name: "Dawood Equities Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DFSM", name: "Dewan Farooque Spinning Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DGKH", name: "D G Khan Cement Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DMID", name: "Diamond Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DMTE", name: "D.M. Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DNTX", name: "Din Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DOL", name: "Descon Oxychem Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DOLM", name: "Dolmen City REIT", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DOST", name: "Dost Steels Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DSIL", name: "DS Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DWAE", name: "Dewan Automotive Engineering Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DWLP", name: "Dawood Lawrencepur Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DWSU", name: "Dewan Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DWTX", name: "Dewan Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "DYNE", name: "Dynea Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ECOP", name: "Ecopack Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EFGH", name: "Intermarket Securities Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EFUA", name: "EFU Life Assurance Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EFUI", name: "EFU General Insurance Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EIBL", name: "Escorts Investment Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ELCM", name: "Elahi Cotton Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ELCT", name: "Elahi Cotton Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ELSP", name: "Ellcot Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EMCO", name: "Emco Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ENGP", name: "Engro Powergen Qadirpur Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ENGR", name: "Engro Fertilizers Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EPCL", name: "Engro Polymer & Chemicals Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EPCL_p", name: "Engro Polymer & Chemicals Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Preferred Stock" },
  { symbol: "EQMD", name: "First Equity Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "EXID", name: "Exide Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FAIN", name: "Fateh Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FARS", name: "Faran Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FASP", name: "Faisal Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FAST", name: "Fast Cables Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FATF", name: "Fatima Fertilizer Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FAUC", name: "Fauji Cement Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FAUF", name: "Fauji Fertilizer Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FAUJ", name: "Fauji Foods Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FCEL", name: "First Capital Equities Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FCEM", name: "Fecto Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FCIB", name: "First Credit And Investment Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FERO", name: "Ferozsons Laboratories Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FERZ", name: "Feroze1888 Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FFLM", name: "First Fidelity Leasing Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FIRS", name: "First Dawood Investment Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FNEL", name: "First National Equities Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FPMM", name: "First Paramount Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FRCE", name: "Frontier Ceramics Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FRIE", name: "FrieslandCampina Engro Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FTMM", name: "First Treet Manufacturing Company Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FTSP", name: "Fateh Sports Wear Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FYBL", name: "Faysal Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FYCC", name: "Flying Cement Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "FZCL", name: "Fazal Cloth Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GAMN", name: "Gammon Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GATX", name: "Gadoon Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GGGL", name: "Ghani Global Glass Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHAD", name: "Ghandhara Nissan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHAI", name: "Ghani Chemical Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHAN", name: "Ghani Gases Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHAR", name: "Gharibwal Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHAZ", name: "Ghazi Fabrics International Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHGL", name: "Ghani Glass Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GHIN", name: "Ghandhara Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GLAX", name: "GlaxoSmithKline Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GLOB", name: "Globe Residency REIT", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GNTY", name: "Ghandhara Tyre and Rubber Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GOCL", name: "GOC Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GRAL", name: "Grays Leasing Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GTRO", name: "Gatron Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GULA", name: "Gul Ahmed Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GULF", name: "Pak Gulf Leasing Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GULS", name: "Gulistan Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GUSP", name: "Gulshan Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "GVGL", name: "Ghani Value Glass Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HABA", name: "Habib Adm Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HABI", name: "Habib Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HABM", name: "First Habib Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HABS", name: "Habib Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HAFZ", name: "Hafiz Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HALA", name: "Hala Enterprises Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HALE", name: "Haleon Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HASC", name: "Hascol Petroleum Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HATC", name: "Honda Atlas Cars (Pakistan) Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HAWA", name: "Haseeb Waqas Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HBL", name: "Habib Bank Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HBLI", name: "HBL Investment", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Closed-end Fund" },
  { symbol: "HINL", name: "Highnoon Laboratories Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HINO", name: "Hinopak Motors Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HITE", name: "Hi Tech Lubricants Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HLLM", name: "Hallmark Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HMB", name: "HabibMetro Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HOEC", name: "Hoechst Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HPWR", name: "Hub Power Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HRTX", name: "Hira Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HUMN", name: "Hum Network Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "HUSI", name: "Hussain Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IBFL", name: "Ibrahim Fibres Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IBLH", name: "IBL HealthCare Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IBLM", name: "First IBL Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ICCI", name: "ICC Industries Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IDES", name: "Ideal Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IDTX", name: "Idrees Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IGI", name: "IGI Insurance Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IGIL", name: "Igi Life Insurance Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IMAG", name: "Image Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "IMPE", name: "Imperial Sugar Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INDM", name: "Indus Motor Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INDY", name: "Indus Dyeing & Manufacturing Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INL", name: "786 Investment Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INTA", name: "International Packaging Films Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INTE", name: "International Steels Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INTI", name: "International Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INTK", name: "International Knitwear Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INTR", name: "Interloop Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "INVS", name: "Invest Capital Investment Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ISML", name: "Ismail Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ITHD", name: "Ittehad Chemicals Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ITTE", name: "ITTEFAQ Iron Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JAND", name: "Janana De Malucho Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JATX", name: "J A Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JAUH", name: "Jauharabad Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JAVA", name: "Javedan Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JDWS", name: "Jdw Sugar Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JGIC", name: "Jubilee General Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JLIC", name: "Jubilee Life Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JSBL", name: "JS Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JSCO", name: "Jahangir Siddiqui & Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JSGC", name: "JS Global Capital Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JSIL", name: "JS Investments Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "JUBL", name: "Jubilee Spinning & Weaving Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KARA", name: "Karam Ceramics Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KELE", name: "K-Electric Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KHAS", name: "Khalid Siraj Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KHPR", name: "Khairpur Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KHPW", name: "Kohinoor Power Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KHYB", name: "Khyber Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KHYT", name: "Khyber Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KML", name: "Kohinoor Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOHC", name: "Kohat Cement Company Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOHI", name: "Kohinoor Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOHN", name: "Kohinoor Energy Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOHP", name: "Kohinoor Power Company Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOHT", name: "Kohinoor Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOTA", name: "KOT Addu Power Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KOTX", name: "Kohat Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "KSBP", name: "KSB Pumps Company Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LDMK", name: "Landmark Spinning Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LEGL", name: "Leiner Pak Gelatine Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LETA", name: "Leather Up Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LOAD", name: "Loads Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LOTT", name: "Lotte Chemical Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LPLP", name: "Lalpir Power Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LSEC", name: "LSE Capital Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LSEF", name: "LSE Financial Services Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LSEV", name: "LSE Ventures Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LUCK", name: "Lucky Cement Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "LUKC", name: "Lucky Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MACP", name: "Macpac Films Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MACT", name: "Macter International Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MAHM", name: "Mahmood Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MASO", name: "Masood Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MATC", name: "Matco Foods Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MCB", name: "MCB Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MCBI", name: "MCB-Arif Habib Savings and Investments Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MDTL", name: "Media Times Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MEHS", name: "Mehran Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MERI", name: "Merit Packaging Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "METS", name: "Metropolitan Steel Corp Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MGAS", name: "Mari Petroleum Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MILM", name: "Millat Tractors Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MITF", name: "Mitchell’s Fruit Farms Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MLKP", name: "Nestle Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MNDW", name: "Mandviwalla Mauser Plastic Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MPKS", name: "Mirpurkhas Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MPLF", name: "Maple Leaf Cement Factory Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MQBT", name: "Maqbool Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MUBR", name: "Murree Brewery Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "MUGH", name: "Mughal Iron & Steel Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NAGI", name: "Nagina Cotton Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NASK", name: "National Silk and Rayon Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NATF", name: "National Foods Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NATR", name: "National Refinery Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NBPK", name: "National Bank of Pakistan", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NCHU", name: "Nishat Chunian Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NCPL", name: "Nishat Chunian Power Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NEXT", name: "Next Capital Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NIIN", name: "Nimir Industrial Chemical Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NIMI", name: "Nimir Resins Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NISH", name: "Nishat Power Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NISM", name: "Nishat Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NOON", name: "Noon Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NTSL", name: "NetSol Technologies Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "NZCM", name: "Nazir Cotton Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OCTO", name: "Octopus Digital Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OGDC", name: "Oil & Gas Development Co. Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OILB", name: "Oilboy Energy Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OLPF", name: "OLP Financial Services Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OLPM", name: "Olp Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OREN", name: "Orient Rental Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ORGA", name: "The Organic Meat Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OTSU", name: "Otsuka Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "OYMP", name: "Olympia Spinning and Weaving Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PACK", name: "Packages Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PACP", name: "Pace Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PAKG", name: "Pak Agro Packaging Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PAKI", name: "Pakistan Aluminium Beverage Cans Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PAKS", name: "Pakistan Stock Exchange Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PAKT", name: "Pakistan Tobacco Co. Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PANT", name: "Panther Tyres Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PARA", name: "Paramount Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PASL", name: "Pervez Ahmed Consultancy Services Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PDCL", name: "Pak Datacom Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PGIL", name: "Pakistan General Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PIAHa", name: "Pakistan International Airline", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PIAHb", name: "Pakistan International Airline Corp", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PIBT", name: "Pakistan International Bulk Terminal Private Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PICT", name: "Pakistan International Container Terminal Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PIL", name: "Picic Insurance Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PION", name: "Pioneer Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PJBO", name: "Punjab Oil Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKCB", name: "Pakistan Cables Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKEG", name: "Pakistan Engineering Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKEL", name: "Pak Elektron Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKIS", name: "Linde Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKLT", name: "Pak Leather Crafts Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKOL", name: "Pakistan Oilfields Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKPL", name: "Pakgen Power Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKPP", name: "Pakistan Paper Products Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKRF", name: "Pakistan Refinery Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PKSV", name: "Pakistan Services Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PNSC", name: "Pakistan National Shipping Corporation", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "POPL", name: "Popular Islamic Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "POWE", name: "Power Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "POWE_p", name: "Power Cement Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Preferred Stock" },
  { symbol: "PPL", name: "Pakistan Petroleum Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PPVC", name: "Pakistan PVC Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PREI", name: "Premier Insurance Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PRES", name: "Premier Sugar Mills and Distillery Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PRET", name: "Premium Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PRIC", name: "Progressive Insurance Co. Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PSO", name: "Pakistan State Oil Company Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PSYN", name: "Pakistan Synthetics Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PTCA", name: "Pakistan Telecommunication Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "PWML", name: "Prosperity Weaving Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "QCFD", name: "Quice Food Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "QUTX", name: "Quetta Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "RAMZ", name: "Rafhan Maize Products Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "REDT", name: "Redco Textiles Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "RELN", name: "Reliance Insurance Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "RELW", name: "Reliance Weaving Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ROSH", name: "Roshan Packages Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "RUBY", name: "Ruby Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "RUPA", name: "Rupali Polyester Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAFB", name: "Sapphire Fibres Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAFE", name: "Safe Mix Concrete Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAIF", name: "Saif Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAIP", name: "Saif Power Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAKS", name: "Sakrand Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SALY", name: "Sally Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SANI", name: "Sana Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SANS", name: "Sanghar Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAPT", name: "Sapphire Textile Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SARW", name: "Saritow Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SAZG", name: "Sazgar Engineering Works Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SBL", name: "Samba Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SCBP", name: "Standard Chartered Bank Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SCHI", name: "Sardar Chemical Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SCPR", name: "Security Papers Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SEAR", name: "The Searle Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SECI", name: "Security Investment Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SECU", name: "Secure Logistics Group Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SERT", name: "Service Industries Textiles Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SERV", name: "Service Global Footwear Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SGPL", name: "SG Power Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHAB", name: "Shabbir Tiles & Ceramics Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHAC", name: "Shadman Cotton Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHAH", name: "Shaheen Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHAS", name: "Shahtaj Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHAT", name: "Shadab Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHEL", name: "Shell Pakistan Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHEZ", name: "Shezan International Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHJT", name: "Shahtaj Textile Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHKS", name: "Shakarganj Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHMS", name: "Shahmurad Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHMT", name: "Shams Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SHZT", name: "Shahzad Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SICH", name: "Sitara Chemical Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SIEG", name: "Siemens Pakistan Engineering Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SIHL", name: "Shifa International Hospitals Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SIPE", name: "Sitara Peroxide Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SMOD", name: "Sindh Modaraba Management Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SNAB", name: "Sindh Abadgar’s Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SONA", name: "Soneri Bank Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SSOM", name: "SS Oil Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "STPL", name: "Siddiqsons Tin Plate Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "STRA", name: "Sitara Energy Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "STYL", name: "Stylers International Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SUHA", name: "Suhail Jute Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SUIN", name: "Sui Northern Gas Pipelines Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SUIS", name: "Sui Southern Gas Co Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SUNT", name: "Sunrays Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SURC", name: "Suraj Cotton Mills Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SVCI", name: "Service Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SYMM", name: "Symmetry Group Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SYNT", name: "Synthetic Products Enterprises", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "SYSE", name: "Systems Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TAGS", name: "Tariq Glass Industries Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TARI", name: "Tariq Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TATX", name: "Tata Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TCLD", name: "Telecard Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "THAL", name: "Thal Industries Corporation Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "THLI", name: "Thal Industries Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "THTA", name: "Thatta Cement Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TNDW", name: "Tandlianwala Sugar Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TOWL", name: "Towellers Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TPFL", name: "Tri Pack Films Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TPLC", name: "TPL Corp Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TPLE", name: "TPL REIT Fund I Unit", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Unit" },
  { symbol: "TPLI", name: "Tpl Insurance Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TPLR", name: "TPL Properties Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TPLT", name: "Tpl Trakker Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRBK", name: "Trust Securities & Brokerage Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TREE", name: "Treet Battery Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRET", name: "Treet Corporation Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRGP", name: "TRG Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRIS", name: "First Tri-Star Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRSP", name: "Tri-Star Power Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "TRUM", name: "Trust Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UBL", name: "United Bank Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UDLI", name: "UDL International Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UDLN", name: "UDL International Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UNIA", name: "Unicap Modaraba", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UNIT", name: "Unity Foods Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UNTD", name: "United Insurance Company of Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UNVI", name: "Universal Insurance Company Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UPFL", name: "Unilever Pakistan Foods Limited", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "UTDS", name: "United Distributors Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "WAHN", name: "Wah Noble Chemicals Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "WAVE", name: "Waves Singer Pakistan Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "WAVS", name: "Waves Home Appliances Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "WCTL", name: "WorldCall Telecom Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "YOUS", name: "Yousaf Weaving Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ZEET", name: "J.K. Spinning Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ZILL", name: "ZIL Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ZJEE", name: "ZAHIDJEE Textile Mills Ltd", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
  { symbol: "ZTL", name: "Zephyr Textiles Ltd.", exchange: "PSX", mic_code: "XKAR", country: "Pakistan", currency: "PKR", type: "Common Stock" },
];
